# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Jeff Turman
tagline:             'Library Geekin\''
description:         'I speak in code and build fantastic toys. I also try to make data fun and informative.'
url:                 http://zensense.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jeff Turman
  url:               https://twitter.com/outtastyle
  email:             turmanator@email.arizona.edu

# Custom vars
version:             1.0.0
